version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    platform: linux/amd64
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_ROOT_HOST: '%' 
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    expose: 
      - 3307