version: '3'
services:
  mysql: 
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3307
      MYSQL_PASSWORD: root
    ports:
      - 3307:3307
    expose: 
      - 3307
